[package]
name = "trico"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
axum-extra = { version = "0.10.1", features = ["typed-header"] }
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.47", features = ["derive"] }
constant_time_eq = "0.4.2"
eyre = "0.6.12"
hex = { version = "0.4.3", features = ["serde"] }
parking_lot = "0.12.4"
positioned-io = "0.3.4"
rand = "0.9.2"
rc-zip-tokio = "4.2.7"
reqwest = { version = "0.12.23", default-features = false, features = ["json", "charset", "http2", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha2 = "0.10.9"
tokio = { version = "1.47.1", features = ["fs", "macros", "process", "rt-multi-thread"] }
toml_edit = { version = "0.23.4", features = ["serde"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
